### ISSUE TITLE
Is there still the intent to add Android support?

### ISSUE THREAD

**Issue by 509dave16** [wix/react-native-invoke#1]
Hey, @talkol ! I was wondering if Android support for this package is still in the works? If you need someone to help with adding the Android support, I would be interested. Thanks!

**Comment by talkol** [comment]
Hey, you are more than welcome to help with the android version. 

Right now @rotemmiz leads the android efforts for this library and detox (the library we use this in), and I'm sure he'll be happy merge in whatever you can contribute.

If you want to brainstorm some implementations directions you're more than welcome to bring them up here.

**Comment by rotemmiz** [comment]
Hey @509dave16 , what did you have in mind ?

Our intent (when we get to it) is to try implementing it as close as possible to iOS. The main differencne will be function overloading, where we didn't make our minds up yet on how to design the API:
- adding explicit types as parameters when invoking
- trying to loop over all overloads and find the best match

I'd love to hear what you think.

**Comment by 509dave16** [comment]
@talkol and @rotemmiz, my apologies for replying late to your comments. I honestly don't have a direction yet. It will take me some time to analyze the iOS implementation to understand the overall pattern and how it could be implemented for Android in Java. I will certainly keep in mind what @rotemmiz mentioned. My main reason for reaching out is I saw a disparity between React Native and NativeScript when it came to accessing Native Apis. And I have an app idea that would potentially require communicating with the system calendars of iOS and Android.

**Comment by talkol** [comment]
@509dave16 When using React Native to access native API you would normally write a native module that will wrap the native functionality in JS. The documentation for iOS is [here](http://facebook.github.io/react-native/docs/native-modules-ios.html) and the documentation for Android is [here](http://facebook.github.io/react-native/docs/native-modules-android.html).

react-native-invoke lets you skip this step by interfacing directly with native API though JS using reflection. It sounds to me like react-native-invoke isn't the best approach for simply accessing the calendar. Why don't you want to write a native module instead?

The use-cases where react-native-invoke is useful are very specific and outlined in this [blog post](https://medium.com/@talkol/invoke-any-native-api-directly-from-pure-javascript-in-react-native-1fb6afcdf57d#.vtahud8vu).. I'm not sure you fall in any of them :)

**Comment by 509dave16** [comment]
@talkol I thought you might say that! I had previously read your blog post on the use cases of react-native-invoke. I just mainly want to be lazy. You are right though. I should take the narrow road of creating a native module I guess ;) . Thanks for your feedback!

**Comment by rotemmiz** [comment]
@509dave16 you can follow the Android implementation progress here
https://github.com/wix/react-native-invoke/tree/android

**Comment by rotemmiz** [comment]
@509dave16, Android support is live, would love some feedback.
Closing the issue.

**Comment by 509dave16** [comment]
@rotemmiz When I get a chance, I'll give it a whirl. I appreciate the work you put into adding Android support!
